openapi: "3.0.2"
info:
  title: Gaming Platform
  version: "1.0"
servers:
  - url: https://127.0.0.1:8000
paths:
  /users/:
    post:
      summary: Регистрация пользователя
      tags:
        - Authentication
      operationId: signUp
      parameters:
        - in: header
          name: X-CSRFToken
          description: CSRF token
          required: true
          schema:
            type: string
            example: saf141kncaskn214
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#components/schemas/UserForSignUp"
            
      responses:
        202:
          description: Ссылка была выслан на почту
          content:
            text/plain:
              schema:
                properties:
                  detail:
                    type: string
                    example: Код был выслан на почту
        403:
          description: Запрос был послан от авторизованного пользователя
          content:
            text/plain:
              schema:
                properties:
                  detail:
                    type: string
                    example: You do not have permission to perform this action
        400:
          description: Поля не прошли валидацию
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/FieldsValidation"
        default:
          description: Все остальное
    put:
      summary: Подтверждение регистрации
      tags:
        - Authentication
      operationId: confirmSignUp
      parameters:
        - in: header
          name: X-CSRFToken
          description: CSRF token
          required: true
          schema:
            type: string
            example: saf141kncaskn214
      requestBody:
        required: true
        content:
          text/plain:
            schema:
              type: object
              required:
                - key
              properties:
                key:
                  type: string
                  example: Qmasmfjajfj128141841hjafhh
      responses:
        200:
          description: Успешная регистрация
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/User"
        400:
          description: Срок действия ключа истек или он неправильный
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/NonFieldError"
        403:
          description: Запрос был послан от авторизованного пользователя
  /key/{key}/:
    get:
      summary: Проверка ключа.
      tags:
        - PasswordChange
      operationId: checkKey
      parameters:
        - in: header
          name: X-CSRFToken
          description: CSRF token
          required: true
          schema:
            type: string
            example: saf141kncaskn214
        - in: path
          name: key
          required: true
          schema:
            type: string
            example: Qmasmfjajfj128141841hjafhh
      responses:
        200:
          description: Ключ принят
          content:
            text/plain:
              schema:
                type: object
                properties:
                  key:
                    type: string
                    example: Qmasmfjajfj128141841hjafhh
        404:
          description: Время действия ключа истекло или он неверен
          content:
            text/plain:
              schema:
                type: object
                properties:
                  code:
                    type: array
                    items:
                      $ref: "#/components/schemas/FieldError"
        403:
          description: Запрос был послан от авторизованного пользователя
          content:
            text/plain:
              schema:
                properties:
                  detail:
                    type: string
                    example: You do not have permission to perform this action
        default:
          description: Все остальное
  /user/session/:
    post:
      summary: Авторизация пользователя
      tags:
        - Authentication
      operationId: login
      parameters:
        - in: header
          name: X-CSRFToken
          description: CSRF token
          required: true
          schema:
            type: string
            example: saf141kncaskn214
      requestBody:
        required: true
        content:
          text/plain:
            schema:
              type: object
              required:
                - username
                - password
              properties:
                username:
                  type: string
                  example: kirin
                password:
                  type: string
                  example: qwert1234
      responses:
        200:
          description: Успешная авторизация
          content:
            text/plain:
              schema:
                properties:
                  username:
                    type: string
                    example: kirin
        400:
          description: Поля не прошли валидацию
          content:
            text/plain:
              schema:
                type: object
                properties:
                  non_field_errors:
                    type: array
                    items:
                      $ref: "#/components/schemas/NonFieldError"
        403:
          description: Запрос был послан от авторизованного пользователя
          content:
            text/plain:
              schema:
                properties:
                  detail:
                    type: string
                    example: You do not have permission to perform this action
        default:
          description: Все остальное
    put:
      summary: Выйти из аккаунта
      tags:
        - Authentication
      operationId: logout
      parameters:
        - in: header
          name: X-CSRFToken
          description: CSRF token
          required: true
          schema:
            type: string
            example: saf141kncaskn214
      responses:
        200:
          description: Успешный выход
        403:
          description: Запрос был послан от неавторизованного пользователя
          content:
            text/plain:
              schema:
                properties:
                  detail:
                    type: string
                    example: You do not have permission to perform this action
        default:
          description: Все остальное
  /user/checker/:
    get:
      summary: Проверка, авторизован ли юзер
      tags:
        - Authentication
      responses:
        200:
          description: Авторизован
        403:
          description: Не авторизован
    
  /user/password/:
    put:
      summary: Смена пароля
      tags:
        - PasswordChange
      operationId: changePassword
      parameters:
        - in: header
          name: X-CSRFToken
          description: CSRF token
          required: true
          schema:
            type: string
            example: saf141kncaskn214
      requestBody:
        required: true
        content:
          text/plain:
            schema:
              type: object
              required:
                - currentPassword
                - newPassword
              properties:
                currentPassword:
                  type: string
                  example: qwert1234
                newPassword:
                  type: string
                  example: zxcasdf
      responses:
        200:
          description: Успешная смена пароля
          content:
            text/plain:
              schema:
                properties:
                  detail:
                    type: string
                    example: Пароль был успешно изменён
        400:
          description: Поля не прошли валидацию
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/FieldsValidation"
        403:
          description: Запрос был послан от неавторизованного пользователя
          content:
            text/plain:
              schema:
                properties:
                  detail:
                    type: string
                    example: You do not have permission to perform this action
        default:
          description: Все остальное
  
  /user/help/link/:
    post:
      summary: Забыли пароль. Отправить ссылку на почту
      tags:
        - PasswordChange
      operationId: sendCodePassword
      parameters:
        - in: header
          name: X-CSRFToken
          description: CSRF token
          required: true
          schema:
            type: string
            example: saf141kncaskn214
      requestBody:
        required: true
        content:
          text/plain:
            schema:
              type: object
              required:
                - email
              properties:
                email:
                  type: string
                  example: rt@gmail.com
      responses:
        202:
          description: Ссылка отправлена
          content:
            text/plain:
              schema:
                properties:
                  detail:
                    type: string
                    example: Ссылка была выслана на почту
        400:
          description: Почта не зарегистрирована
          content:
            text/plain:
              schema:
                properties:
                  email:
                    type: array
                    items:
                      $ref: "#/components/schemas/FieldError"
        default:
          description: Все остальное
  
  /user/help/password/:
    put:
      summary: Смена забытого пароля
      tags:
        - PasswordChange
      operationId: changeForgotPassword
      parameters:
        - in: header
          name: X-CSRFToken
          description: CSRF token
          required: true
          schema:
            type: string
            example: saf141kncaskn214
      requestBody:
        required: true
        content:
          text/plain:
            schema:
              type: object
              required:
                - password
                - key
              properties:
                password:
                  type: string
                  example: qwert1234
                key:
                  type: string
                  example: Qmasmfjajfj128141841hjafhh
      responses:
        200:
          description: Успешная смена пароля
        400:
          description: Пароли не прошли валидацию или срок действия ссылки истек
          content:
            text/plain:
              schema:
                type: object
                properties:
                  non_field_errors:
                    type: array
                    items:
                      $ref: "#/components/schemas/FieldsValidation"
        default:
          description: Все остальное
  /user/friend/:
    post:
      summary: Отправка заявки в друзья или ее принятие
      tags:
        - Friends
      operationId: inviteFriend
      parameters:
        - in: header
          name: X-CSRFToken
          description: CSRF token
          required: true
          schema:
            type: string
            example: saf141kncaskn214
      requestBody:
        required: true
        content:
          text/plain:
            schema:
              type: object
              required:
                - accepter
              properties:
                accepter:
                  type: string
                  example: kirin
      responses:
        201:
          description: Заявка была успешно отправлена
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/FriendshipStatus"
        202:
          description: Заявка была отправлена, пользователи стали друзьями, т.к. существовала входящая заявка(принятие заявки, если просто)
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/FriendshipStatus"
        400:
          description: Поля не прошли валидацию
        403:
          description: Запрос от неавторизованного пользователя
        default:
          description: Все остальное
    put:
      summary: Отменить заявку или удалить друга
      tags:
        - Friends
      operationId: inviteFriend
      parameters:
        - in: header
          name: X-CSRFToken
          description: CSRF token
          required: true
          schema:
            type: string
            example: saf141kncaskn214
      requestBody:
        required: true
        content:
          text/plain:
            schema:
              type: object
              required:
                - accepter
              properties:
                accepter:
                  type: string
                  example: kirin
      responses:
        200:
          description: Заявка отменена
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/FriendshipStatus"
        202:
          description: Пользователь удален из друзей
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/FriendshipStatus"
        400:
          description: Поля не прошли валидацию
        403:
          description: Запрос от неавторизованного пользователя
        default:
          description: Все остальное

  /user/{username}/friend:  
    get:
      summary: Получить список друзей пользователя
      operationId: getFriendList
      tags:
        - Friends
      parameters:
        - in: header
          name: X-CSRFToken
          description: CSRF token
          required: true
          schema:
            type: string
            example: saf141kncaskn214
        - in: path
          required: true
          name: username
          description: Имя пользователя
          schema:
            type: string
            example: kirin
      responses:
        200:
          description: Успешно получен список друзей
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Friends"
        400:
          description: Поля не прошли валидацию
        403:
          description: Запрос от неавторизованного пользователя
        default:
          description: Все остальное
  /users/prefix/{value}/:
    get:
      summary: Получить список пользователей, который начинаются на {value}
      operationId: findUsers
      tags:
        - Friends
      parameters:
        - in: header
          name: X-CSRFToken
          description: CSRF token
          required: true
          schema:
            type: string
            example: saf141kncaskn214
        - in: path
          name: findValue
          description: Значение, по которому искать пользователя
          required: true
          schema:
            type: string
            example: kir
      responses:
        200:
          description: Ответ с пользователями
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Friends"
        404:
          description: Не нашлось пользователей
        403:
          description: Запрос от неавторизованного пользователя
  /user/friendship/{username}/:
    get:
      summary: Получить статус дружбы с пользователем
      operationId: getFriendship
      tags:
        - Friends
      parameters:
          - in: header
            name: X-CSRFToken
            description: CSRF token
            required: true
            schema:
              type: string
              example: saf141kncaskn214
          - in: path
            name: username
            description: Имя пользователя
            required: true
            schema:
              type: string
              example: kirin
      responses:
        200:
          description: Ответ со статусом дружбы
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/FriendshipStatus"
        default:
          description: Все остальное
    

      

components:
  schemas:
    UserForSignUp:
      type: object
      properties:
        username:
          type: string
          example: kirin
        password:
          type: string
          example: asd124af
        email:
          type: string
          example: q@gmail.com
        phoneNumber:
          type: string
          example: "+74447779911"
        
    User:
      type: object
      properties:
        username:
          type: string
          example: kirin
        email:
          type: string
          example: q@gmail.com
        phoneNumber:
          type: string
          example: "+74447779911"
    FieldsValidation:
      type: object
      properties:
        field_name:
          type: array
          items:
            $ref: "#/components/schemas/FieldError"
        non_field_errors:
          type: array
          items:
            $ref: "#/components/schemas/NonFieldError"
    FieldError:
      type: string
      example: Данное имя пользователя уже используется
          
    NonFieldError:
      type: string
      example: Пароли должны совпадать!
    FriendshipStatus:
      type: object
      properties:
        detail:
          type: string
          example: Заявка успешно отправлена
    Friends:
      type: array
      items:
        $ref: "#/components/schemas/Friend"
    Friend:
      type: object
      properties:
        username:
          type: string
          example: kirin
        photo:
          type: string
          example: (poka net example, potom dobavlu)



