version: '3.8'

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: gamingplatform
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: SeMeN4565
    ports:
      - "5432:5432"
    volumes:
      - pgdbdata:/var/lib/postgresql/data/
    networks:
      - djangonetwork
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    networks:
      - djangonetwork
  web:
    build:
      context: ./backend
      dockerfile: Dockerfile.django
    container_name: django-container
    volumes:
      - ./backend:/app 
    environment:
      - DJANGO_ALLOWED_HOSTS=127.0.0.1,localhost
      - CELERY_BROKER_URL=redis://redis:6379/2
      - CELERY_RESULT_BACKEND=redis://redis:6379/2
    command:
      - sh
      - -c
      - |
        /usr/local/bin/wait-for-it.sh db:5432 -t 5 --
        /usr/local/bin/wait-for-it.sh redis:6379 -t 5 --
        python manage.py makemigrations --noinput
        python manage.py migrate --noinput
        gunicorn gamingPlatform.asgi -k uvicorn.workers.UvicornWorker -c gunicorn_config.py --reload --access-logfile -
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    restart: always
    links:
      - db:db
      - redis:redis
    networks:
      - djangonetwork
  celery:
    build:
      context: ./backend
      dockerfile: Dockerfile.django
    volumes:
      - /app
    command: 
      - sh
      - -c
      - start-celery.sh
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/2
      - CELERY_RESULT_BACKEND=redis://redis:6379/2
    ports:
      - "5555:5555"
    depends_on:
      - db
      - redis
      - web
    networks:
      - djangonetwork
  # nginx_backend:
  #   image: nginx:latest
  #   container_name: nginx_backend
  #   volumes:
  #     - ./nginx/nginx.conf:/etc/nginx/nginx.conf
  #     - ./nginx/ssl:/etc/nginx/ssl
  #   ports:
  #     - "1212:1212"
  #   depends_on:
  #     - web
  #     - celery
volumes:
  pgdbdata: null
networks:
  djangonetwork:
    driver: bridge