version: '3.8'

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: gamingplatform
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: SeMeN4565
    ports:
      - "5432:5432"
    volumes:
      - pgdbdata:/var/lib/postgresql/data/
    networks:
      - djangonetwork
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    networks:
      - djangonetwork
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: django-container
    volumes:
      - .:/app
    environment:
      - DJANGO_ALLOWED_HOSTS=127.0.0.1,localhost
    command: ["sh", "-c", "/usr/local/bin/wait-for-it.sh db:5432 -t 5 -- /usr/local/bin/wait-for-it.sh redis:6379 -t 5 -- python manage.py makemigrations --noinput && python manage.py migrate --noinput && daphne -e ssl:8000:server.key:server.crt gamingPlatform.asgi:application"]
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    restart: always
    links:
      - db:db
      - redis:redis
    networks:
      - djangonetwork
volumes:
  pgdbdata: null
networks:
  djangonetwork:
    driver: bridge