http_server:
  host: "localhost"
  port: "8000"
  timeout: 4s
  idle_timeout: 30s
postgres:
  port: ${POSTGRES_PORT}
  host: ${POSTGRES_HOST}
  user: ${POSTGRES_USER}
  password: ${POSTGRES_PASSWORD}
  db_name: ${POSTGRES_DB}
redis:
  addr: ${REDIS_ADDRESS}
  password: ${REDIS_PASSWORD}
  db: ${REDIS_DB}
  username: ${REDIS_USERNAME}
auth:
  secret_word: ${SECRET_WORD}
  session_expiration: 744h
  session_cookie_name: "sessionID"
  csrftoken_cookie_name: "csrftoken"
  csrftoken_header_name: "X-CSRFTOKEN"
  user_session_context_key: "userSession"